feat(build): build components in specific order

diff --git a/.github/workflows/publish-package.yml b/.github/workflows/publish-package.yml
--- a/.github/workflows/publish-package.yml
+++ b/.github/workflows/publish-package.yml
@@ -52,7 +52,35 @@ jobs:
         run: yarn install
 
       - name: Create building of components
-        run: yarn build
+        run: |
+          echo "Building packages in specific order"
+
+          ORDERED_COMPONENTS=("form" "icon-font" "button")
+
+          for component in "${ORDERED_COMPONENTS[@]}"; do
+            echo "Building @flash-global66/$component"
+            yarn build $component
+            
+            # Verificar si la construcción fue exitosa
+            if [ $? -ne 0 ]; then
+              echo "Error building $component"
+              exit 1
+            fi
+          done
+
+          echo "Build remaining packages"
+
+          ALL_COMPONENTS=$(find components -maxdepth 1 -mindepth 1 -type d -exec basename {} \;)
+
+          for component in $ALL_COMPONENTS; do
+            # Verificar si el componente ya fue construido
+            if [[ ! " ${ORDERED_COMPONENTS[@]} " =~ " $component " ]] && [[ ! " ${ORDERED_COMPONENTS[@]} " =~ " g-$component " ]]; then
+              echo "Building @flash-global66/$component"
+              yarn build $component
+            fi
+          done
+
+          echo "All components built successfully"
 
       - name: Check existing tags
         id: check-tags
